@startuml

title __EXECUTORS's Class Diagram__\n

  package  {
    package com.habitrpg.android.habitica {
      package com.habitrpg.android.habitica.executors {
        class JobExecutor {
            {static} - INITIAL_POOL_SIZE : int
            {static} - MAX_POOL_SIZE : int
            {static} - KEEP_ALIVE_TIME : int
            {static} - KEEP_ALIVE_TIME_UNIT : TimeUnit
            - workQueue : BlockingQueue<Runnable>
            - threadPoolExecutor : ThreadPoolExecutor
            - threadFactory : ThreadFactory
            + JobExecutor()
            + execute()
        }
      }
    }
  }
  

  package  {
    package com.habitrpg.android.habitica {
      package com.habitrpg.android.habitica.executors {
        class JobThreadFactory {
            {static} - THREAD_NAME : String
            - counter : int
            + newThread()
        }
      }
    }
  }
  

  package  {
    package com.habitrpg.android.habitica {
      package com.habitrpg.android.habitica.executors {
        interface PostExecutionThread {
            {abstract} + getScheduler()
        }
      }
    }
  }
  

  package  {
    package com.habitrpg.android.habitica {
      package com.habitrpg.android.habitica.executors {
        interface ThreadExecutor {
        }
      }
    }
  }
  

  package  {
    package com.habitrpg.android.habitica {
      package com.habitrpg.android.habitica.executors {
        class UIThread {
            + UIThread()
            + getScheduler()
        }
      }
    }
  }
  

  JobExecutor -up-|> ThreadExecutor
  JobExecutor +-down- JobThreadFactory
  JobThreadFactory -up-|> ThreadFactory
  UIThread -up-|> PostExecutionThread


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
