@startuml

title __AUTH's Class Diagram__\n

  package  {
    package com.habitrpg.android.habitica {
      package com.habitrpg.android.habitica.models {
        package com.habitrpg.android.habitica.models.auth {
          class LocalAuthentication {
              + userID : String
              ~ username : String
              ~ email : String
              + getEmail()
              + setEmail()
              + getUsername()
              + setUsername()
          }
        }
      }
    }
  }
  

  package  {
    package com.habitrpg.android.habitica {
      package com.habitrpg.android.habitica.models {
        package com.habitrpg.android.habitica.models.auth {
          class UserAuth {
              - username : String
              - password : String
              - confirmPassword : String
              - email : String
              + getUsername()
              + setUsername()
              + getPassword()
              + setPassword()
              + getConfirmPassword()
              + setConfirmPassword()
              + getEmail()
              + setEmail()
          }
        }
      }
    }
  }
  

  package  {
    package com.habitrpg.android.habitica {
      package com.habitrpg.android.habitica.models {
        package com.habitrpg.android.habitica.models.auth {
          class UserAuthResponse {
              - apiToken : String
              - token : String
              - newUser : Boolean
              - id : String
              + getToken()
              + setToken()
              + getApiToken()
              + setApiToken()
              + getId()
              + setId()
              + getNewUser()
              + setNewUser()
          }
        }
      }
    }
  }
  

  package  {
    package com.habitrpg.android.habitica {
      package com.habitrpg.android.habitica.models {
        package com.habitrpg.android.habitica.models.auth {
          class UserAuthSocial {
              - network : String
              + getNetwork()
              + setNetwork()
              + getAuthResponse()
              + setAuthResponse()
          }
        }
      }
    }
  }
  

  package  {
    package com.habitrpg.android.habitica {
      package com.habitrpg.android.habitica.models {
        package com.habitrpg.android.habitica.models.auth {
          class UserAuthSocialTokens {
              - client_id : String
              - access_token : String
              + getClient_id()
              + setClient_id()
              + getAccess_token()
              + setAccess_token()
          }
        }
      }
    }
  }
  

  LocalAuthentication -up-|> RealmObject
  UserAuthSocial o-- UserAuthSocialTokens : authResponse


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
