@startuml

title __HELPERS's Class Diagram__\n

  package  {
    package com.habitrpg.android.habitica {
      package com.habitrpg.android.habitica.helpers {
        class NumberAbbreviatorTest {
            - context : Context
            + setUp()
            + testThatItDoesntAbbreviatesSmallNumbers()
            + testThatItAbbreviatesThousand()
            + testThatItAbbreviatesMillion()
            + testThatItAbbreviatesBillion()
            + testThatItAbbreviatesThousandWithoutAdditionalDecimals()
            + voidtestThatitRoundsCorrectly()
        }
      }
    }
  }
  

  package  {
    package com.habitrpg.android.habitica {
      package com.habitrpg.android.habitica.helpers {
        class PopupNotificationsManagerTest {
            - context : Context
            + setUp()
            + itDoesNothingWhenNotificationsListIsEmpty()
            + itShouldNotDisplayNotificationsThatAreNotLoginIncentives()
            + itShouldDisplayADialogueForANotification()
            + itShouldNotDisplayANotificationTwice()
        }
      }
    }
  }
  

  package  {
    package com.habitrpg.android.habitica {
      package com.habitrpg.android.habitica.helpers {
        class RemindersManagerTest {
            + itCreatesRemindersItemFromDateString()
        }
      }
    }
  }
  

  package  {
    package com.habitrpg.android.habitica {
      package com.habitrpg.android.habitica.helpers {
        class UserStatComputerTest {
            - equipmentList : List<Equipment>
            - key : String
            - text : String
            - str : int
            - intStat : int
            - per : int
            - con : int
            + UserStatComputerTest()
            + shouldReturnCorrectEquipmentRow()
            + shouldReturnClassBonusRowWhenClassMatches()
            + ShouldReturnClassBonusRowWhenSpecialClassMatches()
            + shouldNotReturnClassBonusWhenClassDoesNotMatch()
        }
      }
    }
  }
  

  PopupNotificationsManagerTest o-- HostConfig : hostConfig
  PopupNotificationsManagerTest o-- PopupNotificationsManager : popupNotificationsManager
  UserStatComputerTest o-- UserStatComputer : userStatComputer
  UserStatComputerTest o-- Member : user
  UserStatComputerTest o-- Equipment : equipment


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
