@startuml

title __EVENTS's Class Diagram__\n

  package  {
    package com.habitrpg.android.habitica {
      package com.habitrpg.android.habitica.events {
        class BoughtGemsEvent {
            + NewGemsToAdd : int
            + BoughtGemsEvent()
        }
      }
    }
  }
  

  package  {
    package com.habitrpg.android.habitica {
      package com.habitrpg.android.habitica.events {
        class DisplayTutorialEvent {
            + tutorialText : String
            + tutorialTexts : List<String>
            + canBeDeferred : boolean
        }
      }
    }
  }
  

  package  {
    package com.habitrpg.android.habitica {
      package com.habitrpg.android.habitica.events {
        class HabitScoreEvent {
            + Up : boolean
        }
      }
    }
  }
  

  package  {
    package com.habitrpg.android.habitica {
      package com.habitrpg.android.habitica.events {
        class OpenMysteryItemEvent {
        }
      }
    }
  }
  

  package  {
    package com.habitrpg.android.habitica {
      package com.habitrpg.android.habitica.events {
        class SelectClassEvent {
            + isInitialSelection : boolean
            + currentClass : String
        }
      }
    }
  }
  

  package  {
    package com.habitrpg.android.habitica {
      package com.habitrpg.android.habitica.events {
        class ShareEvent {
            + sharedMessage : String
            + shareImage : Bitmap
        }
      }
    }
  }
  

  package  {
    package com.habitrpg.android.habitica {
      package com.habitrpg.android.habitica.events {
        class ShowCheckinDialog {
            + nextUnlockText : String
        }
      }
    }
  }
  

  package  {
    package com.habitrpg.android.habitica {
      package com.habitrpg.android.habitica.events {
        class ShowConnectionProblemEvent {
            + title : String
            + message : String
            + ShowConnectionProblemEvent()
        }
      }
    }
  }
  

  package  {
    package com.habitrpg.android.habitica {
      package com.habitrpg.android.habitica.events {
        class ShowSnackbarEvent {
            + leftImage : Drawable
            + title : String
            + text : String
            + specialView : View
            + rightIcon : Drawable
            + rightTextColor : int
            + rightText : String
        }
      }
    }
  }
  

  package  {
    package com.habitrpg.android.habitica {
      package com.habitrpg.android.habitica.events {
        class TaskTappedEvent {
        }
      }
    }
  }
  

  package  {
    package com.habitrpg.android.habitica {
      package com.habitrpg.android.habitica.events {
        class UserSubscribedEvent {
        }
      }
    }
  }
  

  DisplayTutorialEvent o-- TutorialStep : step
  HabitScoreEvent o-- Task : habit
  ShowCheckinDialog o-- Notification : notification
  ShowSnackbarEvent o-- SnackbarDisplayType : type
  TaskTappedEvent o-- Task : Task


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
