@startuml

title __SCANNER's Class Diagram__\n

  package  {
    package com.habitrpg.android.habitica {
      package com.habitrpg.android.habitica.prefs {
        package com.habitrpg.android.habitica.prefs.scanner {
          class IntentIntegrator {
              {static} + REQUEST_CODE : int
              {static} + DEFAULT_TITLE : String
              {static} + DEFAULT_MESSAGE : String
              {static} + DEFAULT_YES : String
              {static} + DEFAULT_NO : String
              {static} + PRODUCT_CODE_TYPES : Collection<String>
              {static} + ONE_D_CODE_TYPES : Collection<String>
              {static} + QR_CODE_TYPES : Collection<String>
              {static} + DATA_MATRIX_TYPES : Collection<String>
              {static} + ALL_CODE_TYPES : Collection<String>
              {static} - TAG : String
              {static} - BS_PACKAGE : String
              {static} + TARGET_BARCODE_SCANNER_ONLY : List<String>
              {static} - BSPLUS_PACKAGE : String
              {static} + TARGET_ALL_KNOWN : List<String>
              - activity : Activity
              - moreExtras : Map<String, Object>
              - title : String
              - message : String
              - buttonYes : String
              - buttonNo : String
              - targetApplications : List<String>
              + IntentIntegrator()
              {static} + parseActivityResult()
              {static} - list()
              + getTitle()
              + setTitle()
              + setTitleByID()
              + getMessage()
              + setMessage()
              + setMessageByID()
              + getButtonYes()
              + setButtonYes()
              + setButtonYesByID()
              + getButtonNo()
              + setButtonNo()
              + setButtonNoByID()
              + getTargetApplications()
              + setTargetApplications()
              + setSingleTargetApplication()
              + getMoreExtras()
              + addExtra()
              + initiateScan()
              + initiateScan()
              + initiateScan()
              + initiateScan()
              # startActivityForResult()
              # startActivityForResult()
              - findTargetAppPackage()
              - showDownloadDialog()
              + shareText()
              + shareText()
              - attachMoreExtras()
          }
        }
      }
    }
  }
  

  package  {
    package com.habitrpg.android.habitica {
      package com.habitrpg.android.habitica.prefs {
        package com.habitrpg.android.habitica.prefs.scanner {
          class IntentResult {
              - contents : String
              - formatName : String
              - rawBytes : byte[]
              - orientation : Integer
              - errorCorrectionLevel : String
              ~ IntentResult()
              ~ IntentResult()
              + getContents()
              + getFormatName()
              + getRawBytes()
              + getOrientation()
              + getErrorCorrectionLevel()
              + toString()
          }
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
