@startuml

title __COMMANDS's Class Diagram__\n

  package  {
    package com.habitrpg.android.habitica {
      package com.habitrpg.android.habitica.events {
        package com.habitrpg.android.habitica.events.commands {
          class BuyRewardCommand {
          }
        }
      }
    }
  }
  

  package  {
    package com.habitrpg.android.habitica {
      package com.habitrpg.android.habitica.events {
        package com.habitrpg.android.habitica.events.commands {
          class ChecklistCheckedCommand {
          }
        }
      }
    }
  }
  

  package  {
    package com.habitrpg.android.habitica {
      package com.habitrpg.android.habitica.events {
        package com.habitrpg.android.habitica.events.commands {
          class EquipCommand {
              + key : String
              + type : String
          }
        }
      }
    }
  }
  

  package  {
    package com.habitrpg.android.habitica {
      package com.habitrpg.android.habitica.events {
        package com.habitrpg.android.habitica.events.commands {
          class FeedCommand {
          }
        }
      }
    }
  }
  

  package  {
    package com.habitrpg.android.habitica {
      package com.habitrpg.android.habitica.events {
        package com.habitrpg.android.habitica.events.commands {
          class HatchingCommand {
          }
        }
      }
    }
  }
  

  package  {
    package com.habitrpg.android.habitica {
      package com.habitrpg.android.habitica.events {
        package com.habitrpg.android.habitica.events.commands {
          class SendNewInboxMessageCommand {
              + message : String
              + userToSendTo : String
              + SendNewInboxMessageCommand()
          }
        }
      }
    }
  }
  

  package  {
    package com.habitrpg.android.habitica {
      package com.habitrpg.android.habitica.events {
        package com.habitrpg.android.habitica.events.commands {
          class TaskCheckedCommand {
              + completed : boolean
          }
        }
      }
    }
  }
  

  package  {
    package com.habitrpg.android.habitica {
      package com.habitrpg.android.habitica.events {
        package com.habitrpg.android.habitica.events.commands {
          class UpdateUserCommand {
              + updateData : Map<String, Object>
          }
        }
      }
    }
  }
  

  package  {
    package com.habitrpg.android.habitica {
      package com.habitrpg.android.habitica.events {
        package com.habitrpg.android.habitica.events.commands {
          class UseSkillCommand {
          }
        }
      }
    }
  }
  

  BuyRewardCommand o-- Task : Reward
  ChecklistCheckedCommand o-- Task : task
  ChecklistCheckedCommand o-- ChecklistItem : item
  FeedCommand o-- Pet : usingPet
  FeedCommand o-- Food : usingFood
  HatchingCommand o-- Egg : usingEgg
  HatchingCommand o-- HatchingPotion : usingHatchingPotion
  TaskCheckedCommand o-- Task : Task
  UseSkillCommand o-- Skill : skill


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
