@startuml

title __TASKS's Class Diagram__\n

  package  {
    package com.habitrpg.android.habitica {
      package com.habitrpg.android.habitica.models {
        package com.habitrpg.android.habitica.models.tasks {
          class Days {
              - taskId : String
              - m : boolean
              - t : boolean
              - w : boolean
              - th : boolean
              - f : boolean
              - s : boolean
              - su : boolean
              {static} + CREATOR : Creator<Days>
              + getT()
              + setT()
              + getW()
              + setW()
              + getTh()
              + setTh()
              + getF()
              + setF()
              + getS()
              + setS()
              + getSu()
              + setSu()
              + getM()
              + setM()
              + getForDay()
              + describeContents()
              + writeToParcel()
              # Days()
              + Days()
              + getTaskId()
              + setTaskId()
          }
        }
      }
    }
  }
  

  package  {
    package com.habitrpg.android.habitica {
      package com.habitrpg.android.habitica.models {
        package com.habitrpg.android.habitica.models.tasks {
          class TaskList {
              + tasks : Map<String, Task>
          }
        }
      }
    }
  }
  

  package  {
    package com.habitrpg.android.habitica {
      package com.habitrpg.android.habitica.models {
        package com.habitrpg.android.habitica.models.tasks {
          class TaskTag {
              ~ id : String
              - tagId : String
              - taskId : String
              + getId()
              + setId()
              + getTag()
              + setTag()
              + getTask()
              + setTask()
              - updatePrimaryKey()
          }
        }
      }
    }
  }
  

  package  {
    package com.habitrpg.android.habitica {
      package com.habitrpg.android.habitica.models {
        package com.habitrpg.android.habitica.models.tasks {
          class TasksOrder {
              ~ habits : List<String>
              ~ dailys : List<String>
              ~ todos : List<String>
              ~ rewards : List<String>
              + getHabits()
              + setHabits()
              + getDailys()
              + setDailys()
              + getTodos()
              + setTodos()
              + getRewards()
              + setRewards()
          }
        }
      }
    }
  }
  

  Days -up-|> Parcelable
  Days -up-|> RealmObject
  TaskTag -up-|> RealmObject
  TaskTag o-- Tag : tag
  TaskTag o-- Task : task


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
